DROP TABLE IF EXISTS Asiakas CASCADE;
DROP TABLE IF EXISTS Esittelysivu CASCADE;
DROP TABLE IF EXISTS Viesti CASCADE;
DROP TABLE IF EXISTS Lukuoikeus CASCADE;
DROP TABLE IF EXISTS Yllapitaja CASCADE;